Update build.gradle
Required to remove 
"Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/graphics/BitmapCompat.class"
Error while Building APK.